In [2]:

import numpy as np

data = np.random.normal(0,1,10)
np.sort(data)

array([-1.71254049, -1.69956442, -1.27372543, -1.21698637, -0.7720429 ,
       -0.53671481, -0.49224799, -0.26087036,  0.22489466,  0.25366582])

In [7]:
i1 = np.argmin(data)

In [8]:
i2 = np.argmax(data) #인덱스값

i1, i2, np.argmin(data), np.argmax(data)

(np.int64(8), np.int64(7), np.int64(8), np.int64(7))

In [ ]:
np.argmin(data), np.argmax(data)


(np.int64(8), np.int64(7))

In [9]:
idx = np.argsort(data)
data[idx][:3]

array([-1.71254049, -1.69956442, -1.27372543])

In [10]:
data = np.random.randint(0,10,(4,6))

In [11]:
data

array([[9, 0, 4, 6, 5, 7],
       [2, 9, 1, 5, 5, 4],
       [7, 3, 4, 7, 6, 3],
       [9, 0, 0, 0, 4, 2]], dtype=int32)

In [16]:
np.sort(data, axis=0)

array([[2, 0, 0, 0, 4, 2],
       [7, 0, 1, 5, 5, 3],
       [9, 3, 4, 6, 5, 4],
       [9, 9, 4, 7, 6, 7]], dtype=int32)

In [17]:
np.sort(data, axis=1)

array([[0, 4, 5, 6, 7, 9],
       [1, 2, 4, 5, 5, 9],
       [3, 3, 4, 6, 7, 7],
       [0, 0, 0, 2, 4, 9]], dtype=int32)

In [18]:
data = np.random.randint(0,10,7)
data

array([1, 5, 2, 1, 3, 5, 4], dtype=int32)

In [22]:
data = np.arange(1,8)
np.random.shuffle(data)
data

array([1, 2, 5, 4, 7, 3, 6])

In [23]:
np.partition(data,3)

array([1, 2, 3, 4, 5, 6, 7])