In [4]:
import numpy as np


# 실습 과제1: NumPy를 활용한 행렬 변형 실습

## 문제 1: 난수 행렬 생성
N = 6과 M = 5로 설정하고, 0과 1 사이의 난수를 사용하여 (N, M) 형태의 행렬 A를 생성하세요.
힌트: np.random.rand() 함수를 사용하세요.


In [5]:
N = 6
M = 5
A = np.random.rand(N,M)

In [6]:
A

array([[0.02926218, 0.84570559, 0.71425074, 0.79205031, 0.2834017 ],
       [0.25669721, 0.7326047 , 0.45952603, 0.35975747, 0.30351464],
       [0.05597992, 0.66404326, 0.90454062, 0.33602716, 0.64235366],
       [0.23719577, 0.49402846, 0.7936777 , 0.68922222, 0.94592451],
       [0.6275195 , 0.23278489, 0.1131215 , 0.39847552, 0.51635778],
       [0.33608339, 0.57747038, 0.35893157, 0.9863446 , 0.59330191]])

In [7]:
A.shape #A.shape는 NumPy에서 배열의 "형태(shape)" 또는 "크기"를 나타내는 속성

(6, 5)

## 문제 2: 새로운 축 추가

행렬 A에 np.newaxis를 사용하여 새로운 축을 추가하고, 결과를 B에 저장하세요. B의 형태는 (N, 1, M)이 되어야 합니다.

In [8]:
B = A[:, None, :] #np.newaxis = None , 같은표현[:, np.newaxis, :] 
B.shape

(6, 1, 5)

문제 3: 슬라이싱을 이용한 특정 요소 변경
행렬 B에서 세 번째 행의 모든 열을 슬라이싱하여 값을 0.3으로 변경하세요.

In [9]:
B[2, :] = 0.3  #B[2 = 세번째행 (0-based index)

In [10]:
B

array([[[0.02926218, 0.84570559, 0.71425074, 0.79205031, 0.2834017 ]],

       [[0.25669721, 0.7326047 , 0.45952603, 0.35975747, 0.30351464]],

       [[0.3       , 0.3       , 0.3       , 0.3       , 0.3       ]],

       [[0.23719577, 0.49402846, 0.7936777 , 0.68922222, 0.94592451]],

       [[0.6275195 , 0.23278489, 0.1131215 , 0.39847552, 0.51635778]],

       [[0.33608339, 0.57747038, 0.35893157, 0.9863446 , 0.59330191]]])


문제 4: 축 위치를 다르게 설정하여 새로운 행렬 생성
np.newaxis를 사용하여 A의 형태를 (1, N, M)로 변형한 결과를 C에 저장하고, (N, M, 1)로 변형한 결과를 D에 저장하세요. 각 행렬의 형태를 출력하여 확인하세요.

In [13]:
C = A[None, :, :]
D = A[:, :, None]


In [14]:
C,D

(array([[[0.02926218, 0.84570559, 0.71425074, 0.79205031, 0.2834017 ],
         [0.25669721, 0.7326047 , 0.45952603, 0.35975747, 0.30351464],
         [0.3       , 0.3       , 0.3       , 0.3       , 0.3       ],
         [0.23719577, 0.49402846, 0.7936777 , 0.68922222, 0.94592451],
         [0.6275195 , 0.23278489, 0.1131215 , 0.39847552, 0.51635778],
         [0.33608339, 0.57747038, 0.35893157, 0.9863446 , 0.59330191]]]),
 array([[[0.02926218],
         [0.84570559],
         [0.71425074],
         [0.79205031],
         [0.2834017 ]],
 
        [[0.25669721],
         [0.7326047 ],
         [0.45952603],
         [0.35975747],
         [0.30351464]],
 
        [[0.3       ],
         [0.3       ],
         [0.3       ],
         [0.3       ],
         [0.3       ]],
 
        [[0.23719577],
         [0.49402846],
         [0.7936777 ],
         [0.68922222],
         [0.94592451]],
 
        [[0.6275195 ],
         [0.23278489],
         [0.1131215 ],
         [0.39847552],
       


문제 5: 슬라이싱을 통해 부분 행렬 변경
행렬 D에서 마지막 세 행의 모든 요소를 0.8로 변경하세요.

In [17]:
D.shape

(6, 5, 1)

In [18]:
D[-3:, :, :] = 0.8 #-3: → 마지막 3개 행 (즉, N-3, N-2, N-1번째 행)

In [19]:
D

array([[[0.02926218],
        [0.84570559],
        [0.71425074],
        [0.79205031],
        [0.2834017 ]],

       [[0.25669721],
        [0.7326047 ],
        [0.45952603],
        [0.35975747],
        [0.30351464]],

       [[0.3       ],
        [0.3       ],
        [0.3       ],
        [0.3       ],
        [0.3       ]],

       [[0.8       ],
        [0.8       ],
        [0.8       ],
        [0.8       ],
        [0.8       ]],

       [[0.8       ],
        [0.8       ],
        [0.8       ],
        [0.8       ],
        [0.8       ]],

       [[0.8       ],
        [0.8       ],
        [0.8       ],
        [0.8       ],
        [0.8       ]]])